server:
  port: 8084
  servlet:
    context-path: '/master-storage/'

master:
  auth:
    jwtSecret: B&E)H@McQfTjWnZr4u7w!z%C*F-JaNdRgUkXp2s5v8y/A?D(G+KbPeShVmYq3t6w
    jwtExpirationMs: 36000000
  api:
    url:
      authuser: 'http://localhost:8083'

spring:
  application:
    name: master-storage-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/master-storage
    username: postgres
    password: dev_router
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost